//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 25.10.2022 9:03:05
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ToDoR.Common.Contracts
{
    public partial class TaskGroups {

        public TaskGroups()
        {
            this.Tasks = new List<Tasks>();
            OnCreated();
        }

        public virtual Guid Id { get; set; }

        public virtual Guid UserId { get; set; }

        public virtual string Name { get; set; }

        public virtual IList<Tasks> Tasks { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
