//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 25.10.2022 9:03:05
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace ToDoR.Common.Contracts
{
    public partial class Tasks {

        public Tasks()
        {
            OnCreated();
        }

        public virtual Guid Id { get; set; }

        public virtual Guid UserId { get; set; }

        public virtual Guid TaskGroupId { get; set; }

        public virtual string Task { get; set; }

        public virtual string Note { get; set; }

        public virtual DateTime? DueDate { get; set; }

        public virtual int? Repeat { get; set; }

        public virtual int? Status { get; set; }

        public virtual DateTime CreatedAt { get; set; }

        public virtual DateTime? DeletedAt { get; set; }

        public virtual Users Users { get; set; }

        public virtual TaskGroups TaskGroups { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
